# Project-local Hi3516CV610 sample parameters.
#
# The project may live anywhere on the Linux build host. Override
# HISI_SDK_SOURCE when the SDK is installed at a different location:
#   make -f board/Makefile HISI_SDK_SOURCE=/path/to/smp/a7_linux/source

HISI_SDK_SOURCE ?= $(HOME)/Hi/hi3516cv610_1020_musl/Hi3516CV610_SDK_V1.0.2.0/smp/a7_linux/source

ifeq ($(PARAM_FILE), )
    PARAM_FILE := $(HISI_SDK_SOURCE)/Makefile.param
    ifeq ($(wildcard $(PARAM_FILE)), )
        $(error HiSilicon SDK Makefile.param not found at $(PARAM_FILE); set HISI_SDK_SOURCE)
    endif
    include $(PARAM_FILE)
endif

################# select sensor type for your sample ###############################
####    SC4336P_MIPI_4M_30FPS_10BIT            #################
####    GC4023_MIPI_4M_30FPS_10BIT             #################
####    SC431HAI_MIPI_4M_30FPS_10BIT           #################
####    SC450AI_MIPI_5M_30FPS_10BIT            #################
####    SC500AI_MIPI_5M_30FPS_10BIT            #################
####    OS04D10_MIPI_4M_30FPS_10BIT            #################
####    SC4336P_MIPI_3M_30FPS_10BIT            #################
####    SC4336P_MIPI_2M_30FPS_10BIT            #################

SENSOR0_TYPE ?= SC4336P_MIPI_4M_30FPS_10BIT
SENSOR1_TYPE ?= SC4336P_MIPI_4M_30FPS_10BIT

################# select board type for your sample ###############################
####    DMEB_BGA                #################
####    DMEB_QFN                #################

BOARD_TYPE ?= DMEB_QFN

CFLAGS += -D$(SENSOR0_TYPE)_SELECT=y
CFLAGS += -D$(SENSOR1_TYPE)_SELECT=y

MPI_LIBS := $(REL_LIB)/libss_mpi.a
MPI_LIBS += $(REL_LIB)/libss_mpi_sysbind.a
MPI_LIBS += $(REL_LIB)/libss_mpi_sysmem.a

ifeq ($(CONFIG_OT_ISP_SUPPORT), y)
MPI_LIBS += $(REL_LIB)/libss_mpi_ae.a
MPI_LIBS += $(REL_LIB)/libss_mpi_isp.a
MPI_LIBS += $(REL_LIB)/libot_mpi_isp.a
MPI_LIBS += $(REL_LIB)/libss_mpi_awb.a
MPI_LIBS += $(REL_LIB)/libdehaze.a
MPI_LIBS += $(REL_LIB)/libextend_stats.a
MPI_LIBS += $(REL_LIB)/libdrc.a
MPI_LIBS += $(REL_LIB)/libldci.a
MPI_LIBS += $(REL_LIB)/libbnr.a
MPI_LIBS += $(REL_LIB)/libcalcflicker.a
MPI_LIBS += $(REL_LIB)/libir_auto.a
MPI_LIBS += $(REL_LIB)/libacs.a
MPI_LIBS += $(REL_LIB)/libsns_sc4336p.a
MPI_LIBS += $(REL_LIB)/libsns_gc4023.a
MPI_LIBS += $(REL_LIB)/libsns_sc431hai.a
MPI_LIBS += $(REL_LIB)/libsns_sc450ai.a
MPI_LIBS += $(REL_LIB)/libsns_sc500ai.a
MPI_LIBS += $(REL_LIB)/libsns_os04d10.a
ifeq ($(CONFIG_OT_ISP_THERMO_SUPPORT),y)
MPI_LIBS += $(REL_LIB)/libss_mpi_thermo.a
endif
ifeq ($(CONFIG_OT_ISP_DUMP_DEBUG_SUPPORT), y)
MPI_LIBS += $(REL_LIB)/libdump_dbg.a
endif
endif

ifeq ($(CONFIG_OT_AIISP_SUPPORT), y)
ifeq ($(CONFIG_OT_AIDESTRIP_SUPPORT), y)
MPI_LIBS += $(REL_LIB)/libss_mpi_aidestrip.a
endif

ifeq ($(CONFIG_OT_AIBNR_SUPPORT), y)
MPI_LIBS += $(REL_LIB)/libss_mpi_aibnr.a
endif
endif
ifeq ($(CONFIG_OT_SVP_SUPPORT), y)
ifeq ($(CONFIG_OT_SVP_SEC_SUPPORT), y)
    MPI_LIBS += $(REL_LIB)/libsvp_acl_sec.a
else
    MPI_LIBS += $(REL_LIB)/libsvp_acl.a
endif
    MPI_LIBS += $(REL_LIB)/libss_mpi_km.a
    MPI_LIBS += $(REL_LIB)/libprotobuf-c.a
endif

ifeq ($(CONFIG_OT_HEIF_SUPPORT), y)
    MPI_LIBS += $(REL_LIB)/libheif.a
    MPI_LIBS += $(REL_LIB)/libfileformat.a
endif

ifeq ($(CONFIG_OT_AUDIO_SUPPORT), y)
AUDIO_LIBA := $(REL_LIB)/libss_mpi_audio.a
AUDIO_LIBA += $(REL_LIB)/libvoice_engine.a
AUDIO_LIBA += $(REL_LIB)/libupvqe.a
AUDIO_LIBA += $(REL_LIB)/libdnvqe.a
AUDIO_LIBA += $(REL_LIB)/libss_mpi_audio_adp.a
AUDIO_LIBA += $(REL_LIB)/libopus.a
AUDIO_ADP_DIR ?= $(PWD)/../audio/adp
endif
COMMON_DIR ?= $(PWD)/../common

INC_FLAGS := -I$(REL_INC)
INC_FLAGS += -I$(REL_INC)
INC_FLAGS += -I$(SDK_PATH)/$(EXTDRV)/es8388

ISP_VERSION := ISP_V2

CFLAGS += -Wall $(INC_FLAGS) -D$(OT_ARCH) -D$(OT_FPGA) -D$(ISP_VERSION)
CFLAGS += -lstdc++
ifneq ($(CONFIG_LLVM), y)
CFLAGS += -lpthread -lm -ldl
endif
CFLAGS += $(LIBS_CFLAGS)
CFLAGS += $(LIBS_EXEC_CFLAGS)
CFLAGS += $(MPP_CFLAGS)
CFLAGS += -DSENSOR0_TYPE=$(SENSOR0_TYPE)
CFLAGS += -DSENSOR1_TYPE=$(SENSOR1_TYPE)
CFLAGS += -DBOARD_TYPE=$(BOARD_TYPE)
CFLAGS += -D__LINUX__ -D__RTSP__

ifeq ($(MEM_SHARE), y)
    CFLAGS += -DSAMPLE_MEM_SHARE_ENABLE
endif

################ select audio codec type for your sample ################
#external acodec
#ACODEC_TYPE ?= ACODEC_TYPE_ES8388
ACODEC_TYPE ?= ACODEC_TYPE_INNER

ifeq ($(ACODEC_TYPE), ACODEC_TYPE_ES8388)
    CFLAGS += -DOT_ACODEC_TYPE_ES8388
endif

ifeq ($(ACODEC_TYPE), ACODEC_TYPE_INNER)
    CFLAGS += -DOT_ACODEC_TYPE_INNER
endif

################ select audio module library type for your sample ################
AUDIO_MODULE_LIB_TYPE ?= AUDIO_LIB_TYPE_STATIC
#AUDIO_MODULE_LIB_TYPE ?= AUDIO_LIB_TYPE_SHARE
ifeq ($(CONFIG_OT_AUDIO_SUPPORT), y)
ifeq ($(AUDIO_MODULE_LIB_TYPE), AUDIO_LIB_TYPE_STATIC)
##### VQE #####
    CFLAGS += -DOT_VQE_USE_STATIC_MODULE_REGISTER
AUDIO_LIBA += $(REL_LIB)/libvqe_res.a
AUDIO_LIBA += $(REL_LIB)/libvqe_record.a
AUDIO_LIBA += $(REL_LIB)/libvqe_hpf.a
AUDIO_LIBA += $(REL_LIB)/libvqe_anr.a
AUDIO_LIBA += $(REL_LIB)/libvqe_aec.a
AUDIO_LIBA += $(REL_LIB)/libvqe_agc.a
AUDIO_LIBA += $(REL_LIB)/libvqe_eq.a
AUDIO_LIBA += $(REL_LIB)/libvqe_talkv2.a
##### AAC #####
AUDIO_LIBA += $(REL_LIB)/libaac_dec.a
AUDIO_LIBA += $(REL_LIB)/libaac_enc.a
AUDIO_LIBA += $(REL_LIB)/libaac_comm.a
AUDIO_LIBA += $(REL_LIB)/libaac_sbr_dec.a
AUDIO_LIBA += $(REL_LIB)/libaac_sbr_enc.a
endif
endif

#########################################################################
#COMM_SRC := $(wildcard $(COMMON_DIR)/*.c)
COMM_SRC := $(wildcard $(COMMON_DIR)/sample_comm_sys.c)
COMM_SRC += $(wildcard $(COMMON_DIR)/sample_comm_isp.c)
COMM_SRC += $(wildcard $(COMMON_DIR)/sample_comm_vi.c)
COMM_SRC += $(wildcard $(COMMON_DIR)/sample_comm_vpss.c)
COMM_SRC += $(wildcard $(COMMON_DIR)/loadbmp.c)
COMM_SRC += $(wildcard $(COMMON_DIR)/ot_confaccess.c)
ifeq ($(CONFIG_OT_AUDIO_SUPPORT), y)
COMM_SRC += $(wildcard $(COMMON_DIR)/sample_comm_audio.c)
endif
COMM_SRC += $(wildcard $(COMMON_DIR)/sample_comm_venc.c)
COMM_SRC += $(wildcard $(COMMON_DIR)/sample_comm_region.c)
COMM_SRC += $(wildcard $(COMMON_DIR)/sample_comm_osd_drawline.c)
COMM_SRC += $(wildcard $(COMMON_DIR)/sample_ipc.c)
COMM_SRC += $(wildcard $(COMMON_DIR)/rtp_enc.c)
COMM_SRC += $(wildcard $(COMMON_DIR)/rtsp_demo.c)
COMM_SRC += $(wildcard $(COMMON_DIR)/rtsp_msg.c)
COMM_SRC += $(wildcard $(COMMON_DIR)/stream_queue.c)
COMM_SRC += $(wildcard $(COMMON_DIR)/utils.c)
COMM_OBJ := $(COMM_SRC:%.c=%.o)
COMM_INC := -I$(COMMON_DIR)
ifeq ($(CONFIG_OT_AUDIO_SUPPORT), y)
COMM_INC += -I$(AUDIO_ADP_DIR)
endif
