set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(HISILICON_TOOLCHAIN_PREFIX "" CACHE STRING "Absolute path and prefix before gcc/g++, for example /opt/toolchain/bin/aarch64-mix210-linux-")
set(HISILICON_SYSROOT "" CACHE PATH "HiSilicon target sysroot")

if (HISILICON_TOOLCHAIN_PREFIX STREQUAL "")
    message(FATAL_ERROR "Set HISILICON_TOOLCHAIN_PREFIX to the full compiler prefix")
endif()

set(CMAKE_C_COMPILER "${HISILICON_TOOLCHAIN_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${HISILICON_TOOLCHAIN_PREFIX}g++")
set(CMAKE_AR "${HISILICON_TOOLCHAIN_PREFIX}ar")
set(CMAKE_STRIP "${HISILICON_TOOLCHAIN_PREFIX}strip")

if (NOT HISILICON_SYSROOT STREQUAL "")
    set(CMAKE_SYSROOT "${HISILICON_SYSROOT}")
    set(CMAKE_FIND_ROOT_PATH "${HISILICON_SYSROOT}")
    set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
endif()
