# Hi3516CV610 musl cross toolchain for example/ only.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(HISILICON_TOOLCHAIN_PREFIX
    "/opt/linux/x86-arm/arm-v01c02-linux-musleabi-gcc/bin/arm-v01c02-linux-musleabi-"
    CACHE STRING "Full compiler prefix including trailing dash")

set(CMAKE_C_COMPILER   "${HISILICON_TOOLCHAIN_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${HISILICON_TOOLCHAIN_PREFIX}g++")
set(CMAKE_AR           "${HISILICON_TOOLCHAIN_PREFIX}ar")
set(CMAKE_STRIP        "${HISILICON_TOOLCHAIN_PREFIX}strip")
set(CMAKE_RANLIB       "${HISILICON_TOOLCHAIN_PREFIX}ranlib")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
